name: autodeploy

on: [push]

jobs:
  autodeploy:
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}


    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          distribution: adopt
    
      - name: Grant execute permission for gradlew
        run: chmod +x mvnw
    
    #     java maven 캐시 불러움
      - name: Maven Cache
        uses: skjolber/maven-cache-github-action@v1.1
        with:
          step: restore
          
      - name: Build with Gradle
        run: ./mvnw clean package
        
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_TOKEN }}
          build-args: |
            DB_PW=${{ secrets.DATABASE_PASSWORD }}
            DB_URL=${{ secrets.DATABASE_URL }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Caching Paketo Build see https://stackoverflow.com/a/66598693/4964553
      # BP_OCI_SOURCE as --env creates the GitHub Container Registry <-> Repository link (https://paketo.io/docs/buildpacks/configuration/#applying-custom-labels)
      # BP_JVM_VERSION 17, because we use Java 17 inside our Maven build but Paketo defaults to 11
      # Explicitely defining the java-native-image buildpack as described here https://paketo.io/docs/howto/java/#configure-the-graalvm-version
      # to pin the GraalVM version (5.12.0 = GraalVM 21.3)
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/my-container-test:latest


      - name: Install flyctl via https://github.com/superfly/flyctl-actions
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy our Spring Boot app to fly.io
        run: flyctl deploy -c fly.toml

    
